apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: helmargo
  namespace: argocd
spec:
  destination:
    namespace: argo-new
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: argo-cd
    helm:
      parameters:
      - name: applicationSet.metrics.serviceMonitor.interval
        value: {{ .Values.applicationSet.metrics.serviceMonitor.interval }}
      valueFiles:
      - values.yaml
    repoURL: https://harbor.shiva.com/chartrepo/test
    targetRevision: 4.8.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
