apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example
spec:
  generators:
  - git:
      repoURL: https://github.com/rshiva777/arg.git
      revision: HEAD
      files:
      - path: "yamls/**.yaml"
  template:
    metadata:
      name: '{{name}}-example'
    spec:
      project: default
      source:
        chart: argo-cd        
        helm: 
          valueFiles:
          - values.yaml
          values: |-
            {{values}}
        repoURL: https://harbor.shiva.com/chartrepo/test
        targetRevision: 4.8.4
      destination:
        server: '{{address}}'
        namespace: default
