apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
  name: nginx
  namespace: argocd
spec:
  destination:
    namespace: test01
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: .
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
