apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appnginx
  namespace: argocd
spec:
  destination:
    namespace: test01
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: https://github.com/rshiva777/argocd.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
